print("Enter the first number:")
fnum = int(input())
print("Enter the second number:")
snum = int(input())
print(fnum + snum)
print(fnum * snum)
print(fnum ** snum)
print(fnum / snum)
print(type(fnum / snum))